cat << 'EOF' > ~/.cloudflared/config.yml
tunnel: 6f536097-7e01-47ac-b4b4-611a11003867
credentials-file: /home/bball_1181/.cloudflared/6f536097-7e01-47ac-b4b4-611a11003867.json

ingress:
  - hostname: thepolka.cloud
    service: http://localhost:8002

  - hostname: resume-generator.thepolka.cloud
    service: http://localhost:8002

  - service: http_status:404
EOF
